services:
  mc-server:
    image: itzg/minecraft-server
    container_name: lifemod-server
    ports:
      - "25565:25565"
    environment:
      - TYPE=PAPER
      - VERSION=1.21.4
      - EULA=TRUE
      - MEMORY=2G
      - ONLINE-MODE=FALSE
    volumes:
      - ./run/server:/data