plugins {
    id 'java'
}

repositories {
    mavenCentral()
    maven { url 'https://repo.xenondevs.xyz/releases' }
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation project(':common')

    compileOnly 'net.md-5:bungeecord-api:1.20-R0.2-SNAPSHOT'

    implementation 'com.github.retrooper:packetevents-bungeecord:2.7.0'
}

processResources {
    def props = [VERSION: rootProject.version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('bungee.yml') {
        expand props
    }
}


