plugins {
    id 'java'
}

repositories {
    mavenCentral()
    maven { url 'https://repo.xenondevs.xyz/releases' }
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url 'https://repo.codemc.io/repository/maven-public/' }
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation project(':common')
    implementation project(':nms:abstraction')
    implementation project(':nms:v1_8_R3')
    implementation project(':nms:v1_12_R1')
    implementation project(':nms:v1_16_R3')
    implementation project(':nms:v1_18_R2')
    implementation project(':nms:v1_20_R3')
    implementation project(':nms:v1_20_R4')
    implementation project(':nms:v1_21_R1')

    compileOnly 'org.spigotmc:spigot-api:1.21.4-R0.1-SNAPSHOT'
    compileOnly 'net.luckperms:api:5.4'

    implementation 'com.github.retrooper:packetevents-spigot:2.7.0'
    implementation 'xyz.xenondevs.invui:invui:1.49'
    implementation 'org.bstats:bstats-bukkit:3.0.2'
    implementation 'com.zaxxer:HikariCP:5.1.0'
    implementation 'org.mindrot:jbcrypt:0.4'
    implementation 'io.netty:netty-buffer:4.1.100.Final'
    implementation 'se.llbit:jo-nbt:1.2.0'
    implementation 'com.squareup.okhttp3:okhttp:3.14.9'
}

processResources {
    def props = [VERSION: rootProject.version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}


