name: Update LOC Badge

on:
  push:
    branches: [v2]

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Count Lines
        id: loc
        run: |
          # Comptage en excluant les fichiers inutiles, les IDE et les dossiers de build
          COUNT=$(find . -type f \
            -not -path '*/.*' \
            -not -name '*.md' \
            -not -path './target/*' \
            -not -path './build/*' \
            -not -path './.gradle/*' \
            -not -path './.idea/*' \
            -not -path './.vscode/*' \
            -not -path './.settings/*' \
            -not -path './nbproject/*' \
            -not -path './run/*' \
            -not -path './runs/*' \
            -not -name '*.iml' \
            -not -name '*.iws' \
            -not -name '*.ipr' \
            -not -name '.classpath' \
            -not -name '.project' \
            -not -name '.DS_Store' \
            | xargs wc -l | tail -1 | awk '{print $1}')
          
          if [ -z "$COUNT" ]; then COUNT=0; fi
          echo "total=$COUNT" >> $GITHUB_OUTPUT

      - name: Update Gist via API
        run: |
          # On prépare le contenu JSON pour le Gist
          JSON_DATA=$(printf '{"files": {"lines.json": {"content": "{\\"lines\\": %d}"}}}' "${{ steps.loc.outputs.total }}")
          
          # Envoi de la mise à jour au Gist spécifique
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GIST_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/gists/c398eb39d86a2f8a0cd9152209391547 \
            -d "$JSON_DATA"